//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoQL.CEP.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NoQL.CEP.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using NoQL.CEP.NewExpressions;
        ///
        ///@@USINGS@@
        ///namespace NoQL.CEP.NewExpressions
        ///{
        ///public static class Extensions
        ///{
        ///
        ///@@EXTCLASS@@
        ///
        ///}
        ///}.
        /// </summary>
        public static string ExtensionTemplate {
            get {
                return ResourceManager.GetString("ExtensionTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using NoQL.CEP.NewExpressions;
        ///using YoloLambda;
        ///@@USINGS@@
        ///namespace YoloLambda
        ///{
        ///		public class YoloRuntime
        ///        {
        ///            public INewCEPExpression Generate()
        ///			{
        ///				@@REFS@@
        ///				return @@RETURN@@;
        ///			}
        ///        }
        ///}.
        /// </summary>
        public static string superTemplateExpr {
            get {
                return ResourceManager.GetString("superTemplateExpr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///using YoloLambda;
        ///
        ///namespace YoloLambda
        ///{
        ///		public class YoloRuntime
        ///        {
        ///            public Func&lt;object, object&gt; Generate()
        ///			{
        ///				return @@RETURN@@;
        ///			}
        ///        }
        ///}.
        /// </summary>
        public static string template {
            get {
                return ResourceManager.GetString("template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using NoQL.CEP.NewExpressions;
        ///using YoloLambda;
        ///
        ///namespace YoloLambda
        ///{
        ///		public class YoloRuntime
        ///        {
        ///            public INewCEPExpression Generate()
        ///			{
        ///				return @@RETURN@@;
        ///			}
        ///        }
        ///}.
        /// </summary>
        public static string templateExpr {
            get {
                return ResourceManager.GetString("templateExpr", resourceCulture);
            }
        }
    }
}
